### PR TITLE
Bumped version to publish bug fix

### PR DESCRIPTION
**Pull request by franciscop-invast**
Following [this PR](https://github.com/alex-shamshurin/sweetalert2-react/pull/12), please accept the changes and make sure to properly publish them to npm so we can use the dependency locally.

Thanks!

### CODE REVIEW

**Comment by franciscop-invast** [comment]
I don't really think this PR has anything to do with the error, it is literally a string change in `package.json`.

**Comment by hariv1505** [comment]
Agreed, seems like 0.7.2 has been released yet this is still marked as 0.7.1? Perhaps I'm missing something...

**Comment by alex-shamshurin** [comment]
I will release it this weekend

**Comment by franciscop-invast** [comment]
@alex-shamshurin could you fix versions please? npm indicates the latest released version is `0.7.2`, however this repository is still in the `0.7.1`. So this PR should be closed, and version `0.7.3` should be released. The correct order is:

1. Prepare release: modify the `package.json` to the version you want released, next would be the `0.7.3`. I believe [this can be done with npm as well](https://docs.npmjs.com/getting-started/publishing-npm-packages#how-to-update-a-package) with `npm version patch`
2. Update repository: `git add . && git commit -m "Latest release with ..." && git push`
3. Publish tags in Github (optional): `git tag 0.7.3 && git push --tags`
4. Publish to npm: `npm publish`

Alternatively, you can use the tool `np` from Sindre Sorhus: [np - A better npm publish](https://github.com/sindresorhus/np)

**Comment by LucidNinja** [comment]
What's happening with the NPM version of this package? NPM says we're at v 0.7.2, but the GitHub release is only 0.4.10 - I have some issues with my version (from NPM, specifically the html propType), which seem to be resolved in the master here, but aren't reflected in the NPM package. Is this package still being maintained?

**Comment by alex-shamshurin** [comment]
Sorry, still have not time to maintain it. This weekend I'll try

**Comment by alex-shamshurin** [comment]
The package was updated

**Pull request closed without merging**
